# Generated by Django 3.1.3 on 2024-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20241204_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.IntegerField(choices=[(1, '질문 게시판'), (2, '자유 게시판'), (3, '토론 게시판')], default=1),
        ),
    ]
