# Generated by Django 3.1.3 on 2024-12-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20241227_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
