# Generated by Django 5.1.4 on 2025-01-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_auto_20241227_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
